### ISSUE TITLE
Potential Bitblas compat with cuda 12.5

### ISSUE THREAD

**Issue by Qubitium** [microsoft/BitBLAS#120]
While doing ci testing for GPTQModel we found that with cuda 12.5, bitblas is generating broken compiled codes via apache/tvm. There are no errors. The end result is no runtime error but cache model gpu code (in .cached folder) generates non-sense using `backend=BACKEND.BITBLAS`: failed our PPL sanity test.  We copied over .cache/generated files from < cuda 12.5 and it works which isolates the issue to cuda 12.5/apache tvm.

**Comment by LeiWang1999** [comment]
Hi @Qubitium , is that happened on A100?, I'll take a look..

**Comment by Qubitium** [comment]
@LeiWang1999  I believe my team tested both 4090 and A100. This happened last week on July 26th so the usig the latest codes from that point. We have tested it since.

**Comment by Qubitium** [comment]
@LeiWang1999  Maybe related to installing cuda 12.5 but nvidia driver is only 12.4?

```
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
```

So multiple team membes and ci has no issue running bitblas unit tests but this one team member installed cuda 12.5 (in their env) with the gpu driver at 12.4 and bitblas would generate bad gpu code.

**Comment by LeiWang1999** [comment]
OK, that's interesting.

**Comment by LeiWang1999** [comment]
Looks like there's a bug of the instruction `__shfl_down`, which is deprecated in the latest CUDA.

```bash
/tmp/tmpjy7j7pn4.cu(458): warning #1444-D: function "__shfl_down(__half, unsigned int, int)" (declared at line 1852 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp) was declared deprecated ("__shfl_down() is deprecated in favor of __shfl_down_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")
    t0[0] = __shfl_down((red_buf0[0]), (8), (32));
```

**Comment by LeiWang1999** [comment]
close as is has been resloved by pr #143
