### ISSUE TITLE
[Feature Request] Enhance Simplification to remove unused function arguments

### ISSUE THREAD

**Issue by LeiWang1999** [microsoft/BitBLAS#215]
Ref to PR #214.

The scheduling template in TL is quite complex because, for different tensor arguments, we need to implement separate TL templates. This complexity arises because TL cannot automatically remove unused tensor arguments, and the tensor arguments cannot be extended as flexibly as needed.

### Expected Behavior:
```python
# Given Program
@T.prim_func
def main(A, B, Scale, C):
    if with_scale:
        f(A, B, Scale, C)
    else:
        f(A, B, C)
```
If `with_scale` is set to `False`, the `Scale` argument should be removed from the function's argument list.

```[tasklist]
### Tasks
- [x] Test Case
- [x] Implement TL.Simplify Pass
```

**Comment by LeiWang1999** [comment]
I think one best solution is to write a new tl prim func pass `tl.Simplify` similar to `tir.Specify`in `3rdparty/tvm/src/tir/ir/specialize.cc`.

**Comment by tzj-fxz** [comment]
Thanks. PR #216 has been created to implement `tl.transform.Simplify` pass and add test case for it.

> I think the best solution is to implement a new tl prim_func pass, such as `tl.Simplify`, similar to `tir.Specialize` found in 3rdparty/tvm/src/tir/ir/specialize.cc.”

**Comment by LeiWang1999** [comment]
Resloved.
